## Não mexer em nada que for relacionado há endpoints, portas e redis
settings:
  map-slot: 4
  map-slot-confirmed: 4
  api-endpoint: "https://api.terax.world/invoices"
  redis:
    host: "redis-19647.c308.sa-east-1-1.ec2.redns.redis-cloud.com"
    port: 19647
    password: "odOmwuzBID24UTE6rb9ABCLvoFKtbnzD"
  redis-channel: "invoice:update"

messages:
  usage: "§cUso: /pay <productSlug> <pix|link>"
  error-http: "§cErro ao criar pagamento (HTTP %code%)"
  error-generic: "§cErro ao processar pagamento."
  qrcode-ready: "§aQRCODE emitido! caso queira cancelar, apenas clique com o botão direito do mouse."
  payment-link:
    text: "§aSeu link de pagamento foi gerado! %clickable%"
    clickable: "§b§nCLIQUE AQUI"
    hover: "§eClique para abrir o link de pagamento"
  qrcode-map-name: "§aQRCODE para pagamento!"
  qrcode-error: "§cErro ao carregar QR Code."
  payment-confirmed: "§aPagamento confirmado!"
  redis-connected: "Conectado ao Redis com sucesso."
  redis-error: "Erro ao conectar Redis"

